//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.net_MVC_TP_7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public int Qtt { get; set; }
        public int Num_Cmd { get; set; }
        public int Num_Art { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Article Article { get; set; }
    }
}
